FROM golang:1.10.3-stretch

RUN apt-get update \
    && apt install apt-transport-https build-essential curl gnupg2 rpm rsync rubygems-integration ruby-dev ruby -qy \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN gem install --no-ri --no-rdoc --quiet fpm

RUN curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | INSTALL_DIRECTORY=/usr/local/bin sh
